# Generated by Django 4.0.3 on 2022-05-06 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoComision',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Estado Comision')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Publicacion')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo Publicacion')),
                ('imagen', models.ImageField(max_length=200, upload_to=None, verbose_name='Imagen')),
                ('cantLikes', models.IntegerField(verbose_name='Cantidad de Likes')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('idTipoCuenta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Tipo Cuenta')),
                ('tipoCuenta', models.CharField(max_length=50, verbose_name='Tipo Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idUser', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to=None, verbose_name='Foto de Perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('tipoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.tipocuenta', verbose_name='Tipo de cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.categoria', verbose_name='Id Categoria')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id user')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idSolicitud', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Id Solicitud')),
                ('usernameArtista', models.CharField(max_length=150, verbose_name='Username Artista')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('idReferecia', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Referencia')),
                ('img_referencia', models.ImageField(max_length=200, upload_to='index', verbose_name='Referencia')),
                ('usernameArtista', models.CharField(max_length=150, verbose_name='Username Artista')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.categoria', verbose_name='Id Categoria')),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.publicacion', verbose_name='Id Publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Perfil')),
                ('seguidos', models.IntegerField(verbose_name='nro Seguidos')),
                ('seguidores', models.IntegerField(verbose_name='nro Seguidores')),
                ('calificacion', models.IntegerField(verbose_name='Calificacion')),
                ('img_header', models.ImageField(blank=True, max_length=200, null=True, upload_to='index', verbose_name='Header')),
                ('biografia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Biografia')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Id user')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('idComision', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comision')),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Artista')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.estadocomision', verbose_name='Id Estado Comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=250, verbose_name='Comentario')),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.publicacion', verbose_name='Id Publicacion')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id user')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_Cliente',
            fields=[
                ('idComision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EscalArt.comision', verbose_name='Id Comision')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Cliente')),
            ],
        ),
    ]
