# Generated by Django 4.0.3 on 2022-05-10 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoComision',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Estado Comision')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idSolicitud', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Id Solicitud')),
                ('usernameArtista', models.CharField(max_length=150, verbose_name='Username Artista')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('idReferecia', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Referencia')),
                ('img_referencia', models.ImageField(max_length=200, upload_to='index', verbose_name='Referencia')),
                ('usernameArtista', models.CharField(max_length=150, verbose_name='Username Artista')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('idComision', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comision')),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Artista')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.estadocomision', verbose_name='Id Estado Comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_Cliente',
            fields=[
                ('idComision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EscalArt.comision', verbose_name='Id Comision')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Cliente')),
            ],
        ),
    ]
