# Generated by Django 4.0.3 on 2022-05-18 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.publicacion', verbose_name='Id publicacion')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario')),
            ],
        ),
    ]
