# Generated by Django 4.0.3 on 2022-05-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0002_guardado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardado',
            name='id',
        ),
        migrations.AddField(
            model_name='guardado',
            name='idGuardado',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False, verbose_name='Id Guardado'),
            preserve_default=False,
        ),
    ]
