# Generated by Django 4.0.3 on 2022-05-20 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0004_remove_publicacion_cantlikes_publicacion_cantlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='seguidos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='seguidores',
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL, verbose_name='nro seguidores'),
        ),
    ]
