# Generated by Django 4.0.3 on 2022-05-22 04:58

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('EscalArt', '0006_publicacion_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion_categoria',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='publicacion_categoria',
            name='idPublicacion',
        ),
        migrations.RemoveField(
            model_name='usuario_categoria',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='usuario_categoria',
            name='idUser',
        ),
        migrations.AddField(
            model_name='perfil',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Publicacion_Categoria',
        ),
        migrations.DeleteModel(
            name='Usuario_Categoria',
        ),
    ]
