# Generated by Django 4.0.3 on 2022-05-23 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0007_remove_publicacion_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
