# Generated by Django 4.0.3 on 2022-05-22 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0008_comentarios_fechacreacion_publicacion_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='cantLikes',
            field=models.ManyToManyField(blank=True, related_name='CommentLikes', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
    ]
