# Generated by Django 4.0.3 on 2022-05-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0009_comentarios_cantlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='EscalArt.comentarios'),
        ),
    ]
