# Generated by Django 4.0.4 on 2022-05-25 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0010_comentarios_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('idPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EscalArt.perfil')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
