# Generated by Django 4.0.3 on 2022-06-01 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0012_chatroom_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='artista',
            field=models.ManyToManyField(related_name='artista', to=settings.AUTH_USER_MODEL, verbose_name='artista'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='cliente',
            field=models.ManyToManyField(related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
    ]
