# Generated by Django 4.0.3 on 2022-06-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0013_chatroom_artista_chatroom_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='cliente',
        ),
    ]
