# Generated by Django 4.0.3 on 2022-06-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0014_remove_chatroom_artista_remove_chatroom_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='img_referencia',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=None, verbose_name='Referencia'),
        ),
    ]
