# Generated by Django 4.0.3 on 2022-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalArt', '0016_rename_usuario_activo_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='showTags',
            field=models.BooleanField(default=False),
        ),
    ]
